/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32l476xx.h"
#include "stm32l476xx_gpio_driver.h"


void Clock_Init(void);
void GPIOx_Init(void);
void Delay(void);

int main(void)
{

	Clock_Init(); /*Clock Initialization 16Mhz*/
	GPIOx_Init(); /*GPIOs Initializations*/

	while(1)
	{

				GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_5);	

				Delay();
	}
}

void Clock_Init(void)
{
	HSI_ON(); /*Turning ON HSI clock*/
	SELECT_HSI(); /*Configuring System Clock at 16MHz*/
	WAIT_HSI_TO_BE_SET();
}

void GPIOx_Init(void)
{

	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_Handle_t GPIO_LED_struct;

	memset(&GPIO_LED_struct,0,sizeof(GPIO_LED_struct));
	GPIO_LED_struct.pGPIOx = GPIOA;
	GPIO_LED_struct.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED_struct.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
	GPIO_LED_struct.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GPIO_LED_struct.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_LED_struct.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_LED_struct.GPIO_PinConfig.GPIO_PinAltFunMode = 0;

	GPIO_Init(&GPIO_LED_struct); /*Initializing LED*/

}

void Delay(void)
{
	/*aprox 200 ms delay to avoid glitches*/
	for(uint32_t i = 0 ; i < 50000 ; i++);
}

